Models/Producten.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DistributiecenterFonq.Models
{
    public class Producten
    {
        [Required(ErrorMessage = "**Je moet een merk invullen")]
        public string Merk { get; set; }
        public string Type { get; set; }
        public string Afmeting { get; set; }
        public int Voorraad { get; set; }
        public int Gewicht { get; set; }
        public int Id { get; set; }
        public string Afbeelding { get; set; }


    }
}

Models/Vestigingvoorraad.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using DistributiecenterFonq.Data_annotations;

namespace DistributiecenterFonq.Models
{
    public class Vestigingvoorraad
    {
        public string Naam { get; set; }
        public int VestigingId { get; set; }

        [Range(0, 2000)]
        [VeelvoudVanTwee]
        public int Voorraad { get; set; }
        public int ProductId { get; set; }
    }
}

Controllers/HomeController.cs
using DistributiecenterFonq.Models;
using DistributiecenterFonq.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DistributiecenterFonq.Controllers
{
    public class HomeController : Controller
    {
        //public ProductenRepository productenRepository = new ProductenRepository();
        private readonly IProductenRepository productenRepository;

        public HomeController(IProductenRepository productenRepository)
        {
            this.productenRepository = productenRepository;   
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult Products()
        {            
            var producten = productenRepository.GetAllProducten();
            return View(producten);
        }
        public ActionResult Add()
        {
            return View(new Producten());
        }

        [HttpPost]
        public ActionResult Add(Producten productModel)
        {
            if (ModelState.IsValid)
            {
                productenRepository.AddNewProduct(productModel);
                return RedirectToAction("Products");
            }
                
            else 
            {
                return View(productModel);
            }    
        }
        public ActionResult Update(int productId)
        {
            return View(productenRepository.GetOneProduct(productId)); 
        }

        [HttpPost]
        public ActionResult Update(Producten productModel)
        {
            productenRepository.UpdateProduct(productModel);
            return RedirectToAction("Products");
        }

        public ActionResult Delete(int productId)
        {
            productenRepository.DeleteProduct(productId);
            return RedirectToAction("Products");
        }
    }
}

Controllers/VestigingController.cs
using DistributiecenterFonq.Models;
using DistributiecenterFonq.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DistributiecenterFonq.Controllers
{
    public class VestigingController : Controller
    {
        private readonly IVestigingRepository vestigingRepository;
       // public VestigingRepository vestigingRepository = new VestigingRepository();
        public ProductenRepository productenRepository = new ProductenRepository();

        public VestigingController(IVestigingRepository vestigingRepository)
        {
            this.vestigingRepository = vestigingRepository;
        }


        //laat de voorraden zien voor alle vestigingen
        public ActionResult ShowVestigingvoorraad(int productId)
        {
            ViewBag.Message = "Voorraad per vestiging:";
            var vestigingvoorraad = vestigingRepository.GetVestigingvoorraad(productId);
            return View(vestigingvoorraad);
        }

        // update per vestiging van een product
        public ActionResult Update(int vestId, int productID)
        {
            return View(vestigingRepository.GetOneVestigingVoorraad(productID, vestId));
        }

        [HttpPost]
        public ActionResult Update(Vestigingvoorraad vestigingvoorraadModel)
        {
            if (ModelState.IsValid) //validatie van de data annotation
            {
                vestigingRepository.UpdateVestigingVoorraad(vestigingvoorraadModel);                
                return RedirectToAction("ShowVestigingvoorraad", new { productId = vestigingvoorraadModel.ProductId });
            }
            else
            {
                return View(vestigingvoorraadModel);
            }
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Add.cshtml
@model DistributiecenterFonq.Models.Producten
@{
    ViewBag.Title = "Add";
}

<h2>Voeg een nieuw product toe:</h2>
@using (Html.BeginForm("Add", "Home"))
{
<table>
        @Html.EditorForModel()
        @Html.ValidationMessageFor(m => m.Merk)
        
</table>

        <button type="submit">Add</button>
}

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Fonq<br />
    Reactorweg 53<br />
    <abbr title="Phone">P:</abbr>
    085 - 888 68 55
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Welkom bij</h1>
    <p><img src="~/Images/fonq.jpeg"></p>
</div>

Views/Home/Products.cshtml
@model List<DistributiecenterFonq.Models.Producten>

@{
    ViewBag.Title = "Products";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>De volgende producten zijn beschikbaar: </p>

@Html.ActionLink("Add new product", "Add", "Home")

<table>
    <tr>
        <th class="kopregel">Afbeelding</th>
        <th class="kopregel">Merk</th>
        <th class="kopregel">Type</th>
        <th class="kopregel">Afmeting</th>
        @*<th class="kopregel">Gewicht</th>*@
        <th class="kopregel">Totale voorraad</th>
        <th class="kopregel">Vestigingen</th>
        <th class="kopregel">Update product</th>
        <th class="kopregel">Delete product</th>
    </tr>

    @Html.DisplayForModel()

</table>

Views/Home/Update.cshtml
@model DistributiecenterFonq.Models.Producten
@{
    ViewBag.Title = "Update";
}

<h2>Update het product:</h2>
@using (Html.BeginForm("Update", "Home"))
{
    <table>
        @Html.EditorForModel()
    </table>

    <button type="submit">Update product</button>
}

Views/Shared/DisplayTemplates/Producten.cshtml
@model DistributiecenterFonq.Models.Producten

    <tr>
        <td><img src="~/Images/@Model.Afbeelding" height="100" width="100"></td>
        <td>@Model.Merk</td>
        <td>@Model.Type</td>
        <td>@Model.Afmeting</td>
        @*<td>@p.Gewicht</td>*@
        <td>@Model.Voorraad</td>
        <td>@Html.ActionLink("Winkelvoorraad", "ShowVestigingvoorraad", "Vestiging", new { productID = Model.Id }, null)</td>
        <td>@Html.ActionLink("Update product", "Update", "Home", new { productID = Model.Id }, null)</td>
        <td>@Html.ActionLink("Delete product", "Delete", "Home", new { productID = Model.Id }, null)</td>
    </tr>

Views/Shared/DisplayTemplates/Vestigingvoorraad.cshtml
@model DistributiecenterFonq.Models.Vestigingvoorraad

    <tr>
        @*<td>@v.VestigingId</td>
            <td>@v.ProductId</td>*@
        <td>@Model.Naam</td>
        <td>@Model.Voorraad</td>
        <td>@Html.ActionLink("Update voorraad", "Update", "Vestiging", new { vestId = Model.VestigingId, productID = Model.ProductId }, null)</td>
    </tr>

Views/Shared/EditorTemplates/Producten.cshtml
@model DistributiecenterFonq.Models.Producten

<tr>
    <td>@Html.HiddenFor(m => m.Id)</td>
    <td>@Html.LabelFor(m => m.Afbeelding)</td>
    <td>@Html.LabelFor(m => m.Merk)</td>
    <td>@Html.LabelFor(m => m.Type)</td>
    <td>@Html.LabelFor(m => m.Afmeting)</td>
    <td>@Html.HiddenFor(m => m.Voorraad)</td>
</tr>
<tr>
    <td>@Html.HiddenFor(m => m.Id)</td>
    <td>@Html.TextBoxFor(m => m.Afbeelding)</td>
    <td>@Html.TextBoxFor(m => m.Merk)</td>
    <td>@Html.TextBoxFor(m => m.Type)</td>
    <td>@Html.TextBoxFor(m => m.Afmeting)</td>
   
    <td>@Html.HiddenFor(m => m.Voorraad)</td>
</tr>

Views/Shared/EditorTemplates/Vestigingvoorraad.cshtml
@model DistributiecenterFonq.Models.Vestigingvoorraad

<tr>
    <td>@Html.LabelFor(m => m.Naam)</td>
    <td>@Html.LabelFor(m => m.Voorraad)</td>
</tr>
<tr>
    @Html.HiddenFor(m => m.VestigingId)
    @Html.HiddenFor(m => m.ProductId)
    <td>@Html.TextBoxFor(m => m.Naam)</td>
    <td>@Html.TextBoxFor(m => m.Voorraad)</td>
    @Html.ValidationMessageFor(m => m.Voorraad, "", new { @class = "errormessage" })
</tr>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Fonq</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    @*<span class="icon-bar"></span>*@
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fonq", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Products", "Products", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Fonq</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Vestiging/ShowVestigingvoorraad.cshtml
@model List<DistributiecenterFonq.Models.Vestigingvoorraad>

@{
    ViewBag.Title = "Vestingsvoorraad";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Het product is beschikbaar in de volgende winkels : </p>

<table>
    <tr>
        @*<th class="kopregel">VestigingId</th>
        <th class="kopregel">ProductID</th>*@
        <th class="kopregel">Vestigingsnaam</th>
        <th class="kopregel">Voorraad</th>
        <th class="kopregel">Update voorraad</th>
    </tr>

    @Html.DisplayForModel()

    
</table>

Views/Vestiging/Update.cshtml
@model DistributiecenterFonq.Models.Vestigingvoorraad
@{
    ViewBag.Title = "Update voorraad";
}

<h2>Update het product:</h2>
@using (Html.BeginForm("Update", "Vestiging"))
{
<table>
    <tr>
        <td>@Html.LabelFor(m => m.Naam)</td>
        <td>@Html.LabelFor(m => m.Voorraad)</td>
    </tr>
    <tr>
        @Html.HiddenFor(m => m.VestigingId)
        @Html.HiddenFor(m => m.ProductId)
        <td>@Html.TextBoxFor(m => m.Naam)</td>
        <td>@Html.TextBoxFor(m => m.Voorraad)</td>
        @Html.ValidationMessageFor(m => m.Voorraad, "", new { @class = "errormessage" })
    </tr>
</table>

    <button type="submit">Update voorraad</button>
}